### ISSUE TITLE
how to write/change variables?

### ISSUE THREAD

**Issue by peter2pc** [Spanni26/pyHPSU#28]
Hello and many thanks to this (forked) project!

Reading (for example: "pyHPSU.py -h -c mode_01") is running fine at my raspberr with PiCan2.

But how can I change variables? I havn't any examples, comments or else.

MAybe you can explain with the example of changing heating programm (change "mode_01" from "12" [this is Auto 2] to "11" [this is Auto 1].

many thanks

**Comment by ahermann86** [comment]
Hello,

the non numeric values are not implemented since yet. Someone would have to program that first..
So far you have to do it like this:

My "old version", before i wrote a FHEM/Perl Module, with ELM327 and daemon running:

Mode Auto1:
pyHPSU.py -d HPSUD -c mode_01:11
Mode Auto2:
pyHPSU.py -d HPSUD -c mode_01:12

I looked at this script (canpi.py) briefly and I think that this should also work for your adapter.

For example:
Mode Auto1:
pyHPSU.py -h -c mode_01:11
Mode Auto2:
pyHPSU.py -h -c mode_01:12

...

Axel
